services:

  db:
    build:
      context: "mysql"
      dockerfile: mysql8.0_Dockerfile
    container_name: db
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql:/mysql
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    #command: --default-authentication-plugin=mysql_native_password
    #command: sh -c "bash /mysql/mysql_docker_init.sh"

  php:
    build:
      context: .
      dockerfile: php8.2-fpm-alpine-mysql8.0-Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    ports:
      - "9001:9001"
