services:

  db:
    build:
      context: "mysql"
      dockerfile: mysql8.0_ubuntu22_Dockerfile
    container_name: db
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql:/mysql
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    command: sh -c "bash /mysql/mysql_docker_init.sh && tail -f /dev/null"
