services:

  db:
    build:
      context: "mysql"
      dockerfile: mysql8.0_ubuntu24_Dockerfile
    container_name: dbmysql8_u24
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql:/mysql
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
#    command: sh -c "bash /mysql/docker_init.sh && bash /mysql/mysql8.0_initialize.sh && bash /mysql/mysql8.0_start.sh && tail -f /dev/null"
    #command: sh -c "bash /mysql/docker_init.sh && bash /mysql/mysql8.0_initialize.sh && tail -f /dev/null"
    command: sh -c "bash /mysql/docker_init.sh && tail -f /dev/null"
